# Generated by Django 5.0.6 on 2024-06-28 12:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
        ('myread', '0002_statuspercent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='myread',
            name='myread_myread_per_read_start_read_date_check',
        ),
        migrations.AlterField(
            model_name='statuspercent',
            name='read_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('reading', 'Reading'), ('done', 'Done')], default='pending', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='myread',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('percentage_read__exact', 0), ('start_read_date__isnull', True)), models.Q(('percentage_read__gt', 0), ('start_read_date__isnull', False)), _connector='OR'), name='myread_myread_per_read_start_read_date_check'),
        ),
    ]
