# Generated by Django 5.0.6 on 2024-07-04 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_alter_tag_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='tags',
            field=models.ManyToManyField(related_name='tag', to='book.tag'),
        ),
    ]
