# Generated by Django 5.0.6 on 2024-07-10 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0012_alter_book_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookauthor',
            options={'verbose_name_plural': 'Books and Authors'},
        ),
    ]
